version: '3.8'

services:
  stable-diffusion-webui:
    image: ashleykza/stable-diffusion-webui:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /workspace:/workspace
    ports:
      - "3000:3001"
      - "3010:3011"
      - "3020:3021"
      - "6006:6066"
      - "8888:8888"
    environment:
      JUPYTER_PASSWORD: "Jup1t3R!"
      ENABLE_TENSORBOARD: "1"
    restart: unless-stopped
